<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PlantController extends Controller
{
    #function to get the plant image from trefle api using Genus and species generated by the GPT-3 model
    public function getPlantImage(){
        $trefle_api = getenv('TREFLE_API_KEY');
        $genus_species = 'Fragaria vesca';
        //split string into array
        $genus_species = explode(' ', $genus_species);
        $genus = $genus_species[0];
        $species = $genus_species[1];
        
        //Initialize new curl session, then set options, then excute it, and then close the session
        $curl = curl_init();
        curl_setopt_array($curl, [
            CURLOPT_URL => "https://trefle.io/api/v1/plants/search?token=$trefle_api&q=$genus&q=$species",
            CURLOPT_RETURNTRANSFER => true,
        ]);
        $response = curl_exec($curl);
        curl_close($curl);
    }

}
